# Generated by Django 5.2.1 on 2025-09-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default.png', null=True, upload_to='users/avatars/', verbose_name='头像'),
        ),
    ]
