# Generated by Django 5.2.1 on 2025-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
