# Generated by Django 5.2.1 on 2025-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
