# Generated by Django 5.2.1 on 2025-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(upload_to='courses/course_covers', verbose_name='封面图片链接'),
        ),
    ]
