# Generated by Django 5.2.1 on 2025-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_chapter_chapterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
