# Generated by Django 5.2.1 on 2025-07-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_chapterimage_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='learning.chapter', verbose_name='所属章节'),
        ),
    ]
