# Generated by Django 5.2.1 on 2025-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_chapter_is_published_alter_chapterimage_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='章节富文本内容'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='章节标题'),
        ),
    ]
