# Generated by Django 5.2.1 on 2025-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_coursecategory_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
