# Generated by Django 5.2.1 on 2025-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_chapter_order_course_order_coursecategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
