# Generated by Django 5.2.1 on 2025-09-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_chapter_order_alter_course_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='未命名章节', max_length=200, verbose_name='章节标题'),
        ),
    ]
