# Generated by Django 5.2.1 on 2025-09-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_coursefavorite_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, default='未命名章节', max_length=200, null=True, verbose_name='章节标题'),
        ),
    ]
