# Generated by Django 5.2.1 on 2025-09-14 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_course_rating_course_rating_count_courserating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_views',
            field=models.PositiveIntegerField(default=1, verbose_name='总浏览量'),
        ),
        migrations.CreateModel(
            name='CourseViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='最近浏览时间')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='浏览次数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='learning.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程浏览历史',
                'verbose_name_plural': '课程浏览历史',
                'ordering': ['-last_viewed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
