# Generated by Django 5.2.1 on 2025-09-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_course_total_views_courseviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseviewhistory',
            name='view_count',
            field=models.PositiveIntegerField(default=1, verbose_name='该用户浏览次数'),
        ),
    ]
